shell = { program = "zsh", args = ["-l", "-c", "tmux attach || tmux"]}

[window]
option_as_alt = "Both"
padding = { x = 3, y = 0 }

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "SemiLight" }
bold = { family = "CaskaydiaMono Nerd Font", style = "SemiBold" }
size = 14
